dataset: mot_crowdhuman

crowdhuman_train_split: train_val
train_split: mot17_train_coco
val_split: mot17_train_cross_val_frame_0_5_to_1_0_coco

mot_path_train: data/MOT17
mot_path_val: data/MOT17

resume: models/mot17_crowdhuman_deformable_multi_frame_WithoutInf_lambda1000_6000Abs_80_120/checkpoint_epoch_119.pth
epochs: 120
lr_drop: 90